### ISSUE TITLE
View All Comments for the Post (2)

### ISSUE THREAD

**Issue by uting98** [JiejayLan/unifreefrontend#58]
Technical Background
- User should be able to see all comments for the post on the `IndividualPost` page
- Users should be able to choose the number of comments they want to see in each page

Acceptance Criteria
- Create a component such that it will allow users view all the comments for a speicific post in the `IndividualPost` page. Please see [backend ticket](https://github.com/jinchen1036/rdb-crud-microservice/issues/77)
- Create the pagination component for comment

**Comment by nchen000** [comment]
Should we add pagination to this ticket as well?

**Comment by uting98** [comment]
> Should we add pagination to this ticket as well?

I am thinking should pagination be a separate ticket or in same issue?
