### ISSUE TITLE
User Reply Feature

### ISSUE THREAD

**Issue by songrenzhao** [JiejayLan/unifreefrontend#74]
Technical Background:
- Currently we have comments in each post, we have to allow users to reply free on any post

Issues related:
N/A

Acceptance Criteria:
- Allow users to post and edit reply on a comment

**Comment by nchen000** [comment]
Should we allow the user to edit reply?

**Comment by songrenzhao** [comment]
> Should we allow the user to edit reply?

Yes @nchen000

**Comment by uting98** [comment]
then should we allow user to edit comment? @songrenzhao

**Comment by uting98** [comment]
> > Should we allow the user to edit reply?
> 
> Yes @nchen000

I don't think users should be able to edit their reply, they can just reply more to correct their opinions

**Comment by ethen001** [comment]
@nchen000  Yes, I think we should allow them to edit their replies

**Comment by songrenzhao** [comment]
@nchen000 @ethen001 @uting98 We will add an issue for edit reply. We can close it when we figure our in grooming

**Comment by nchen000** [comment]
> > > Should we allow the user to edit reply?
> > 
> > 
> > Yes @nchen000
> 
> I don't think users should be able to edit their reply, they can just reply more to correct their opinions

I agree with @uting98 , if we don't allow user to edit comment then we should apply the same rules to reply.

**Comment by uting98** [comment]
> > > > Should we allow the user to edit reply?
> > > 
> > > 
> > > Yes @nchen000
> > 
> > 
> > I don't think users should be able to edit their reply, they can just reply more to correct their opinions
> 
> @ethen001 @songrenzhao I agree with @uting98 , if we don't allow user to edit comment then we should apply the same rules to reply.

agree with nan, we can allow users to delete the reply and comment, but we should not allow users to edit
