### ISSUE TITLE
View Comments School Label (1)

### ISSUE THREAD

**Issue by nchen000** [JiejayLan/unifreefrontend#75]
Technical Background:
- identify which school the user is from
- use [Chip](https://material-ui.com/components/chips/) component as a reference

Acceptance Criteria:
- Add `label` which indicates school in [View All Posts](https://github.com/JiejayLan/unifreefrontend/pull/46),  [Individual Post page](https://github.com/JiejayLan/unifreefrontend/pull/48), [View Comments](https://github.com/JiejayLan/unifreefrontend/pull/63)

**Comment by songrenzhao** [comment]
I will break this down into 3 issues. @nchen000

**Comment by songrenzhao** [comment]
Done
